project_id: '834434'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
languages_mapping: &languages_mapping
  two_letters_code:
    pt-BR: pt-BR
files:
  # JSON translation files
  - source: /messages/en/**/*
    translation: /messages/%two_letters_code%/**/%original_file_name%
    languages_mapping: *languages_mapping
