name: Download GitHub Projects
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'
permissions:
  contents: write
jobs:
  download_projects:
    name: Download projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4.2.0

      - name: Download projects
        run: npx tsx scripts/download-all-projects.script.ts

      - name: Commit changes
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git add assets/projects.json
          git commit -m "chore: update projects"
          git push
