name: Download GitHub Projects
on:
  workflow_dispatch:
  schedule:
    - cron: '5 4 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  download_projects:
    name: Download projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v5

      - name: Download projects
        run: npx tsx scripts/download-all-projects.script.ts

      - name: Create Pull Request
        id: cpr
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update projects'
          signoff: true
          branch: feat/update-projects
          delete-branch: true
          title: 'chore: update projects'
          body: |
            This PR updates the projects in the repository.
          assignees: socketsomeone
          reviewers: socketsomeone
          draft: false

      - name: Enable auto-merge for Projects PRs
        run: gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ steps.cpr.outputs.pull-request-url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
