name: Download GitHub Projects
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: write
  pull-requests: write

jobs:
  download_projects:
    name: Download projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4.2.0

      - name: Download projects
        run: npx tsx scripts/download-all-projects.script.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        env:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update projects'
          committer: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>
          author: ${{ github.actor }} <${{ github.actor_id }}+${{ github.actor }}@users.noreply.github.com>
          signoff: false
          branch: example-patches
          delete-branch: true
          title: 'chore: update projects'
          body: |
            This PR updates the projects in the repository.
          assignees: socketsomeone
          reviewers: socketsomeone
          draft: false
